### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by blaziter** [Elisniper/MBD#1]
Hi,
all buttons are invisible but are clickable except emoji one, which is visible. Tried to resolve, but idk where it went wrong.

![image](https://github.com/Elisniper/MBD/assets/85119621/d3707e92-4917-40b2-b369-998da72a155e)

**Comment by Elisniper** [comment]
Discord updated the classes for those 3 icons so my code was clashing with the new one. 

I have updated the theme so they should now be visable again.
